### ISSUE TITLE
Hitting several issues:

### ISSUE THREAD

**Issue by mcfa77y** [roadhump/SublimeLinter-eslint#107]
Despite installing eslint globally, I'm hitting this error:
```
Cannot find module: 'eslint-plugin-babel'
```

I tried to install that package locally and now hit a different error: 
```
RangeError: Maximum call stack size exceeded
    at Referencer.Visitor.visitChildren (/Users/joe/Sites/EST/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js)
    at Referencer.Visitor.visit (/Users/joe/Sites/EST/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/Users/joe/Sites/EST/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
...etc
```

Any help solving these issues would be appreciated. Thanks!

**Comment by mcfa77y** [comment]
The issue was that eslint-plugin-babel was also installed globally keeping it only local resolved the issue.

**Comment by roadhump** [comment]
I can suggest by path `/Users/joe/Sites/EST/node_modules/eslint` that you have `eslint` to be installed locally in your project, so it can't find `eslint-plugin-babel`.

I also suppose that your error is not related to this plugin, it is inside `eslint` or eslint plugin itself. Try to run `eslint` by CLI the same way it is run by plugin and check output.
```
cd project
./node_modules/.bin/eslint file.js
```
