### ISSUE TITLE
Fatal error regarding '__RELATIVE_TO_FOLDER__'

### ISSUE THREAD

**Issue by thebinarypenguin** [roadhump/SublimeLinter-eslint#117]
My Environment

- Debain 8 Jessie 64-bit
- Sublime Text 3 Build 3083
- Sublime​Linter v3.6.1
- Sublime​Linter-contrib-eslint v1.9.2

Linter only works if I open a folder (as opposed to a file).

Examples
- If I open sublime and choose to open a folder and then select a file from the sidebar, it will work
- If I open sublime and choose to open a file, it will not work

Here is a console dump.

```
DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/ethan/.config/sublime-text-3/Packages
state path: /home/ethan/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/ethan/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.201989
startup time: 0.331214
first paint time: 0.342651
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2016-01-31 07:56:13, next run at 2016-01-31 08:56:13 or after
ignored packages updated to: ["SublimeLinter", "Vintage"]
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
SublimeLinter: debug mode: off 
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
ignored packages updated to: ["SublimeLinter-contrib-eslint", "Vintage"]
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter reloaded 
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/home/ethan/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ethan/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/home/ethan/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/home/ethan/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/home/ethan/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 924, in lint_view
    linter.lint(hit_time)
  File "/home/ethan/.config/sublime-text-3/Packages/SublimeLinter/lint/node_linter.py", line 77, in lint
    super(NodeLinter, self).lint(hit_time)
  File "/home/ethan/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1384, in lint
    output = self.run(cmd, self.code)
  File "/home/ethan/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1790, in run
    return self.communicate(cmd, code)
  File "/home/ethan/.config/sublime-text-3/Packages/SublimeLinter-contrib-eslint/linter.py", line 79, in communicate
    if '__RELATIVE_TO_FOLDER__' in cmd and self.filename[0] == self.view.window().extract_variables()['folder'][0]:
KeyError: 'folder'
 
SublimeLinter: -------------------- 
```

**Comment by lpinca** [comment]
I have the same issue. If I manually install an older version it works.
Here is the log:
```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/luigi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/luigi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/luigi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/luigi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/luigi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 924, in lint_view
    linter.lint(hit_time)
  File "/Users/luigi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 77, in lint
    super(NodeLinter, self).lint(hit_time)
  File "/Users/luigi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1384, in lint
    output = self.run(cmd, self.code)
  File "/Users/luigi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1790, in run
    return self.communicate(cmd, code)
  File "/Users/luigi/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-eslint/linter.py", line 79, in communicate
    if '__RELATIVE_TO_FOLDER__' in cmd and self.filename[0] == self.view.window().extract_variables()['folder'][0]:
KeyError: 'folder'
 
SublimeLinter: -------------------- 
```

**Comment by lpinca** [comment]
Version 1.9.1 works fine, so the issue has been introduced here https://github.com/roadhump/SublimeLinter-eslint/commit/18874dd1698e577f5076d9283d091387eb715519

**Comment by roadhump** [comment]
Thanks, I've reverted this commit.

**Comment by thebinarypenguin** [comment]
Just wanted to confirm that the new 1.9.3 version does fix the problem thanks
