### ISSUE TITLE
 eslint-plugin-babel refuses to load

### ISSUE THREAD

**Issue by gigavinyl** [roadhump/SublimeLinter-eslint#139]
Fill your issue here.

For some reason, `eslint-plugin-babel` refuses to load.
#### `SublimeLinter` console output

```
startup, version: 3103 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/gigavinyl/Library/Application Support/Sublime Text 3/Packages
state path: /Users/gigavinyl/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/gigavinyl/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: []
Unable to decode Packages/Material Theme/assets/darker/overlay_bar_horizontal.png
pre session restore time: 0.584537
startup time: 0.667725
first paint time: 0.679764
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin Alignment.Alignment
reloading plugin All Autocomplete.all_views_completions
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin ColorPick.ColorPick
reloading plugin Colorsublime.colorsublime-plugin
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin Git Conflict Resolver.GitConflictResolver
reloading plugin Git-StatusBar.git-statusbar
reloading plugin Git.git_commands
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Spotify.applescript_spotify_player
reloading plugin Spotify.singleton
reloading plugin Spotify.spotify_player
reloading plugin Spotify.status_updater
reloading plugin Spotify.sublime_spotify
reloading plugin Terminality.generic_shell
reloading plugin Terminality.macro
reloading plugin Terminality.progress
reloading plugin Terminality.settings
reloading plugin Terminality.terminality
reloading plugin Terminality.unit_collections
reloading plugin Terminality.utils
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin Babel.Babel
reloading plugin Cheat Sheets.cheat-sheets
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter loaded 
plugins loaded
[Terminality] v0.3.10
SublimeLinter: debug mode: off 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2016-04-11 22:08:38, next run at 2016-04-11 23:08:38 or after
SublimeLinter: eslint: server.js ['/Users/gigavinyl/.nvm/versions/node/v5.7.1/bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
reloading Packages/User/SublimeLinter.sublime-settings
SublimeLinter: eslint: server.js ['/Users/gigavinyl/.nvm/versions/node/v5.7.1/bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint: server.js ['/Users/gigavinyl/.nvm/versions/node/v5.7.1/bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
Failed to load plugin babel: Cannot find module 'eslint-plugin-babel'
Error: Failed to load plugin babel: Cannot find module 'eslint-plugin-babel'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.module.exports.load (/Users/gigavinyl/.nvm/versions/node/v5.7.1/lib/node_modules/eslint/lib/config/plugins.js:116:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (/Users/gigavinyl/.nvm/versions/node/v5.7.1/lib/node_modules/eslint/lib/config/plugins.js:138:21)
    at Object.load (/Users/gigavinyl/.nvm/versions/node/v5.7.1/lib/node_modules/eslint/lib/config/config-file.js:443:21)
    at loadConfig (/Users/gigavinyl/.nvm/versions/node/v5.7.1/lib/node_modules/eslint/lib/config.js:67:33)
    at getLocalConfig (/Users/gigavinyl/.nvm/versions/node/v5.7.1/lib/node_modules/eslint/lib/config.js:129:23) 
```
#### `eslint` output from command line

``` bash
/Users/gigavinyl/Projects/ceres/shared/components/PostListItem/PostListItem.jsx
  42:3  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)
```
#### Additional info if needed (ST version, OS, configuration)

eslint and eslint-plugin have been installed globally and my `.zprofile` is:

``` bash
export NVM_DIR="/Users/gigavinyl/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
nvm use 5
```

Package.json's eslintConfig

``` json
...
"eslintConfig": {
    "parser": "babel-eslint",
    "plugins": [
      "babel",
      "react"
    ],
    "extends": "airbnb",
    "env": {
      "browser": true,
      "node": true
    },
    "ecmaFeatures": {
      "jsx": true,
      "es6": true,
      "classes": true,
      "generators": true,
      "objectLiteralShorthandMethods": true
    },
    "rules": {
      "strict": 0,
      "max-len": [
        1,
        180,
        4
      ],
      "arrow-body-style": [
        0
      ],
      "consistent-return": 0,
      "no-unused-vars": 0,
      "no-use-before-define": 0,
      "generator-star-spacing": 2,
      "babel/generator-star-spacing": 1,
      "babel/new-cap": 1,
      "react/prefer-stateless-function": 0,
      "react/jsx-no-bind": 0
    }
  },
...
```

**Comment by roadhump** [comment]
Your plugin should be installed globally if you use global `eslint`. Does it?
