### ISSUE TITLE
Working from command line but not in ST

### ISSUE THREAD

**Issue by reintroducing** [roadhump/SublimeLinter-eslint#156]
Fill your issue here.

#### `SublimeLinter` console output

SublimeLinter: eslint: MapContainer.jsx ['/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/eslint/lib/cli.js:18
const fs = require("fs"),
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/eslint/bin/eslint.js:29:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10) 

#### `eslint` output from command line

./node_modules/.bin/eslint widget/src/js/components/map/MapContainer.jsx

/Users/mprzybylski/Work/SpotHero/SpotHero-Django/widget/src/js/components/map/MapContainer.jsx
  174:20  error  'setNewSearchData' is missing in props validation  react/prop-types

✖ 1 problem (1 error, 0 warnings)

#### Additional info if needed (ST version, OS, configuration)

ESLint is showing up as an error in the console while it works just fine from the command line. It used to work a while ago and I've just kind of dealt with it since it stopped but its getting to a point where I am missing some of the warnings and have to keep jumping to the terminal to see them. Plus its much easier to see the highlights in my editor versus not and then having to find them. 

Also of note is that I have the scss-lint module installed and those errors/icons do show up correctly in the editor.

Any idea why its no longer working?  I'm on OS X El Capitan v10.11.6, ST build 3126. node version is 4.2.2 and npm v2.14.7. ESLint version in my package.json is 3.5. Any help would be greatly appreciated here as it's really becoming a nuisance that this stopped working.

**Comment by reintroducing** [comment]
Read through ALL the directions again and found my issue. I had to move nvm init from .zshrc into .zprofile. Phew!
