### ISSUE TITLE
Error in SublimeLinter daemon (after updating SublimeLinter 3.9.0 -> 3.10.0) 

### ISSUE THREAD

**Issue by darkred** [roadhump/SublimeLinter-eslint#180]
Using ST3 3148 dev x64 in win10  (1709. Fall Creators Update [16299.15)).
I have ESLint 4.8.0 globally installed (with a .eslintrc.js in C:\Users\User).
I had SublimeLinter 3.9.0 with SublimeLinter-contrib-eslint 1.10.0. 
I had no problem with them.

Today I updated SublimeLinter to v3.10.0 via Package Control.
During the update I got this in console (if it's relevant):
```
Package Control: Installing 1 upgrades
ignored packages updated to: ["ColorHelper", "ConvertToUTF8", "SublimeLinter", "Vintage"]
unloading plugin SublimeLinter.commands
unloading plugin SublimeLinter.sublimelinter
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Upgraded SublimeLinter to 3.10.0
ignored packages updated to: ["ColorHelper", "ConvertToUTF8", "Vintage"]
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
SublimeLinter: debug mode: off 
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
SublimeLinter: daemon detected a reload 
Traceback (most recent call last):
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 379, in generate_menus_async
    text = generate_menu('Context', menus)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\util.py", line 390, in generate_menu
    with open(path, encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Kostas\\AppData\\Roaming\\Sublime Text 3\\Packages\\SublimeLinter\\Context.sublime-menu.template'
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

After that, whenever I open ST3, if it opens with an empty tab, there are no errors in console.
But If I try to open any .js file with ST3, I get the following in console 
-and no lint errors are marked on the file- :
```
SublimeLinter: debug mode: off 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 923, in lint_view
    view_settings = linter.get_view_settings(inline=False)
  File "./python3.3/functools.py", line 251, in wrapper
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 449, in get_view_settings
    settings = self.get_merged_settings()
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 496, in get_merged_settings
    self.replace_settings_tokens(settings)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 590, in replace_settings_tokens
    folders = window.project_data()['folders']
TypeError: 'NoneType' object is not subscriptable
 
SublimeLinter: -------------------- 
```

**Comment by darkred** [comment]
I thought it was caused by SublimeLinter-eslint (like https://github.com/SublimeLinter/SublimeLinter3/issues/404 )
but it proved to be caused by SublimeLinter.
Its new version v3.10.1 fixes the issue.
