### ISSUE TITLE
Linting doesn't work on Windows 8.1

### ISSUE THREAD

**Issue by georgejdli** [roadhump/SublimeLinter-eslint#30]
This is the error message I see in the sublime console when i try to lint a Javascript file:

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 58, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 66, in loop
    self.lint(view_id, timestamp)
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 112, in lint
    self.callback(view_id, timestamp)
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 123, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 917, in lint_view
    linter.lint(hit_time)
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 63, in lint
    is_dep = self.is_dependency()
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 88, in is_dependency
    is_dep = True if self.npm_name == pkg['name'] else False
KeyError: 'name'
 
SublimeLinter: -------------------- 
Writing file /c/Users/Hellfire/code/react-0.12.2/text.js with encoding UTF-8 (atomic)
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 255, in on_post_save
    callback.on_post_save(v)
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 445, in on_post_save
    self.file_was_saved(view)
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 470, in file_was_saved
    self.lint(vid)
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 123, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 917, in lint_view
    linter.lint(hit_time)
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 63, in lint
    is_dep = self.is_dependency()
  File "C:\Users\Hellfire\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 88, in is_dependency
    is_dep = True if self.npm_name == pkg['name'] else False
KeyError: 'name'

```
eslint works fine when I run it from the command line on the JS file.

**Comment by roadhump** [comment]
I Suppose it is a bug of SublimeLinter itself, you should check its issues.
