### ISSUE TITLE
"'Window' object has no attribute 'extract_variables'" when linting

### ISSUE THREAD

**Issue by defrex** [roadhump/SublimeLinter-eslint#54]
Whenever SublimeLinter runs eslint, I get the following (and no linting is done).

```
SublimeLinter: eslint: admin.jsx ['/home/defrex/code/ratemds/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__'] 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/home/defrex/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 58, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/defrex/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 66, in loop
    self.lint(view_id, timestamp)
  File "/home/defrex/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 112, in lint
    self.callback(view_id, timestamp)
  File "/home/defrex/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 123, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/home/defrex/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 919, in lint_view
    linter.lint(hit_time)
  File "/home/defrex/.config/sublime-text-3/Packages/SublimeLinter/lint/node_linter.py", line 78, in lint
    super(NodeLinter, self).lint(hit_time)
  File "/home/defrex/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1375, in lint
    output = self.run(cmd, self.code)
  File "/home/defrex/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1784, in run
    return self.communicate(cmd, code)
  File "/home/defrex/.config/sublime-text-3/Packages/SublimeLinter-contrib-eslint/linter.py", line 80, in communicate
    vars = window.extract_variables()
AttributeError: 'Window' object has no attribute 'extract_variables'
 
SublimeLinter: -------------------- 
```

**Comment by roadhump** [comment]
What version of ST you use?

**Comment by defrex** [comment]
ST3, build 3065

**Comment by pablolmiranda** [comment]
Same for me.

**Comment by roadhump** [comment]
Add check of API, push version 1.5.2

Seems ST versions older than 3080 lack API to find file path relative to project folder. Plugin will still work with `.eslintignore` with old versions of ST, but its paths should be like `**/node_modules/`, instead lf `node_modules/`
