### ISSUE TITLE
Cannot read property 'ecmaFeatures' of undefined

### ISSUE THREAD

**Issue by adriano-di-giovanni** [roadhump/SublimeLinter-eslint#56]
SublimeLinter: eslint: integration.js ['/Users/me/.nvm/v0.10.35/bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__'] 
SublimeLinter: eslint output:
Cannot read property 'ecmaFeatures' of undefined
TypeError: Cannot read property 'ecmaFeatures' of undefined
    at /Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/eslint.js:369:53
    at Array.forEach (native)
    at prepareConfig (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/eslint.js:368:33)
    at EventEmitter.module.exports.api.verify (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/eslint.js:602:18)
    at processText (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/cli-engine.js:231:23)
    at CLIEngine.executeOnText (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/cli-engine.js:371:26)
    at Object.cli.execute (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/cli.js:178:36)
    at configInit.initializeConfig.exitCode (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/bin/eslint.js:13:28)
    at ConcatStream.<anonymous> (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:117:20)

**Comment by roadhump** [comment]
Try to execute eslint in command line, I suppose it is connected with eslint itself, not plugin.
