### ISSUE TITLE
1.5.5 Breaks linting for all JavaScript files.

### ISSUE THREAD

**Issue by uipoet** [roadhump/SublimeLinter-eslint#66]
The following traceback appears in my console whenever opening a JavaScript file:
```
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "/Users/uipoet/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 282, in on_activated
    self.check_syntax(view)
  File "/Users/uipoet/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 209, in check_syntax
    Linter.assign(view, reset=True)
  File "/Users/uipoet/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 745, in assign
    linter = linter_class(view, syntax)
  File "/Users/uipoet/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 56, in __init__
    self.read_manifest(path.getmtime(self.manifest_path))
  File "/Users/uipoet/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 227, in read_manifest
    self.cached_manifest = json.load(codecs.open(self.manifest_path, 'r', 'utf-8'))
  File "./json/__init__.py", line 274, in load
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 368, in raw_decode
  File "./json/scanner.py", line 38, in _scan_once
  File "./json/decoder.py", line 198, in JSONObject
  File "./json/scanner.py", line 38, in _scan_once
  File "./json/decoder.py", line 198, in JSONObject
  File "./json/scanner.py", line 38, in _scan_once
  File "./json/decoder.py", line 198, in JSONObject
  File "./json/scanner.py", line 38, in _scan_once
  File "./json/decoder.py", line 220, in JSONObject
ValueError: Expecting property name enclosed in double quotes: line 47 column 7 (char 1174)
```

**Comment by uipoet** [comment]
Determined this was due to a syntax error in my project's package.json.

**Comment by alemarre** [comment]
If it can help anyone : 
I had a similar issue just because my "package.json" file was in UTF-8 with BOM.
It must be in UTF-8 WITHOUT BOM.
