### ISSUE TITLE
Plugin stopped doing anything since upgrading to eslint 1.6.0

### ISSUE THREAD

**Issue by gotofritz** [roadhump/SublimeLinter-eslint#96]
Hi. I'm on OS X.

I've been using the plugin for a while, worked great. Now I have just updated eslint globally `npm install -g eslint` and the plugin is not doing anything anymore. It keeps telling me there are no errors and the debug window doesn't show any activity. I have tried uninstalling and reinstalling both sublime linter and SublimeLinter-eslint (in the right order). Running eslint from the CLI on the same file generates tons of errors.

This is my siblimeLinter.sublime-settings - note that I had to set `@disable: false` manually because it had mysteriously set itself to true. And I have restarted ST3 afterwards.

    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/ProjectIcons/ProjectIcons.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "eslint": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "squiggly underline",
        "no_column_highlights_line": false,
        "passive_warnings": true,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }

This is the output of the console before I do any linting. Selecting "Lint this file" from the menu doesn't change anything - no activity in the console. Doing "Next error" brings the "No lint errors" alert but still no activity in the console.

    SublimeLinter: eslint linter loaded 
    reloading plugin User.vintageous_toggler
    plugins loaded
    SublimeLinter: debug mode: on 
    SublimeLinter: temp directory: /var/folders/7h/mstbycln2tsgh2g4nz496n5h0000gn/T/SublimeLinter3-me 
    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 272, in on_modified
        callback.on_modified(v)
      File "bh_core in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 867, in on_modified
      File "bh_core in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 903, in ignore_event
    AttributeError: 'NoneType' object has no attribute 'ignore_all'
    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
        callback.on_selection_modified(v)
      File "bh_core in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 884, in on_selection_modified
      File "bh_core in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/BracketHighlighter.sublime-package", line 903, in ignore_event
    AttributeError: 'NoneType' object has no attribute 'ignore_all'
    reloading Packages/User/SublimeLinter.sublime-settings
    Package Control: Skipping automatic upgrade, last run at 2015-10-12 16:35:11, next run at 2015-10-12 17:35:11 or after

Thanks

**Comment by gotofritz** [comment]
OK stopped and started ST3 a couple of times and again the linter shows up as "disabled" in the settings and when I to "toggle linter...". I changed it manually to false in SublimeLinter.sublime-settings - it still appears as disabled in the "Toggle Linter..." list. It still does nothing when do "Lint this View". But when I save the settings file it does lint the file - but it shows the output only in the console, not in the gutter. In fact it keeps insisting there are "no lint errors" when do "Next error"

Here's the console output when I save the settings file and it does the linting

    reloading Packages/User/SublimeLinter.sublime-settings
    SublimeLinter: chdir not set or invalid, using /Users/ME/work/vw/vw-sa-ihdcc-demo 
    SublimeLinter: eslint: gulpfile.sample.js ['/usr/local/bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__'] 
    SublimeLinter: eslint output:
    gulpfile.sample.js: line 5, col 1, Error - Unexpected var, use let or const instead. (no-var)
    ... lots more errors

**Comment by gotofritz** [comment]
It looks like ST3 was getting confused about syntax of the file - although it had it down as "Javascript" in the View menu, it didn't really. Manually resetting it made SublimeLinter kick into action.
